services:
  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "${APP_SERVER_PORT}:8080"
    env_file:
      - .env
    profiles:
      - prod

  postgres:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    profiles:
      - dev
      - prod

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    profiles:
      - dev

