services:
  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "${APP_SERVER_PORT}:8080"
    profiles:
      - prod
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

  postgres:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    profiles:
      - dev
      - prod
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    profiles:
      - dev
