services:

  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - dev
      - prod
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    profiles:
      - dev

  keycloak:
    image: keycloak/keycloak
    restart: always
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - app
    volumes:
      - ./src/main/resources/keycloak/import:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"
    profiles:
      - dev
      - prod
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${KC_DB_SCHEMA}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./src/main/resources/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - prod

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./src/main/resources/monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./src/main/resources/monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./src/main/resources/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    profiles:
      - prod

  app:
    image: app:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - ${APP_SERVER_PORT}:8080
    profiles:
      - prod
    environment:
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}

volumes:
  postgres_data:
